{% set version = "3.0.0" %}

package:
  name: kisn_pylab
  version: {{ version }}

source:
  git_rev: master
  git_url: https://github.com/bartulem/KISN-PyLab.git
  
requirements:
  host:
    - python 3.7
    - setuptools

  run:
    - python 3.7
    - ipykernel 5.1.*	
    - ipython 7.12.*		
    - ipywidgets 7.5.*	
    - jedi 0.16.*
    - json5 0.9.*	
    - jsonschema 3.2.*	
    - jupyter 1.0.*	
    - jupyterlab 1.2.*
    - matplotlib 3.1.*	
    - notebook 6.0.*	
    - numpy	
    - pandas 1.0.*	
    - pandocfilters 1.4.*	
    - pickleshare 0.7.*
    - pip 20.0.*
    - scipy 1.4.*	
    - tqdm 4.42.*
    - plotly
    - scikit-learn
    - astropy
    - numba

test:
  imports:
    - kisn_pylab

about:
  home: https://github.com/bartulem/KISN-PyLab
  license: MIT LICENSE
  license_file: LICENSE
